[project]
name = "threatx-api-client"
version = "1.9.0"
description = "A client library for the ThreatX API"
authors = [{name = "Nikita Ratskov", email = "nikita.ratskov@threatx.com"}]
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
readme = "README.md"
dependencies = [
    "aiohttp~=3.13",
    "aiodns~=3.5",
]

[dependency-groups]
dev = [
    "ruff~=0.14",
    "coverage~=7.10",
    "pytest~=8.4",
    "deptry~=0.23",
]
release = [
    "python-semantic-release~=10.4"
]

[tool.deptry.per_rule_ignores]
DEP003 = ["threatx_api_client"]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.ruff]
src = ["src", "tests"]
lint.select = ["ALL"]
lint.ignore = [
    "E501",
    "PLR2004",
    "D104",
    "D100",
    "INP001",
    "FBT",
    "TD",
    "PT",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.semantic_release]
version_toml = [
    "pyproject.toml:project.version"
]
major_on_zero = false
branch = "main"
build_command = "uv run ruff check"
