[project]
name = "threatx-api-client"
version = "1.8.1"
description = "A client library for the ThreatX API"
authors = [
    {name = "Nikita Ratskov", email = "nikita.ratskov@threatx.com"}
]
license = {text = "Apache-2.0"}
readme = "README.md"
dependencies = [
    "aiohttp (>=3.9)",
    "aiodns (>=3.2.0,<4.0.0)",
]
requires-python = ">=3.10,<4"

[tool.poetry.group.dev.dependencies]
ruff = "^0.12"
coverage = "^7.10"
deptry = "^0.23"

[tool.poetry.group.release.dependencies]
python-semantic-release = "^10.3"
pytest = "^8.4"

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
src = ["threatx_api_client", "tests"]
lint.select = ["ALL"]
lint.ignore = [
    "E501",
    "PLR2004",
    "D104",
    "D100",
    "INP001",
    "FBT",
    "TD",
    "PT",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.semantic_release]
version_toml = [
    "pyproject.toml:project.version",

]
major_on_zero = false
branch = "main"
build_command = "poetry run ruff check"
