name: Prepare Python environment
description: "Python environment preparation"

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Install project dependencies
      shell: bash
      run: uv sync --all-groups
